sudo: required

language: php
php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - '8.0'

matrix:
  allow_failures:
    - php: nightly

script:
  - composer install
  - composer ci

notifications:
  email: false
